version: '3.8'

services:
  events:
    image: events
    build:
      context: .
      dockerfile: SportHire.Events.API/Dockerfile
    container_name: events_api
    ports:
      - 5301:5301
    networks:
      - sporthire-net

networks:
  sporthire-net:
    external: true

